### ISSUE TITLE
Making JuliaDB optional dependency or making new package for adding suppoer for JuliaDB

### ISSUE THREAD

**Issue by racinmat** [r3tex/CQLdriver.jl#10]
JuliaDB is currently going through time of frozen dependencies, they experience obscure bug and in order to catch it, all dependiencies have upper bounds on their versions, some of them being several years old. 
This makes this package almost unusable with newer Julia or newer package versions even when user does not need JuliaDB. 

Although it's always posiible to fork it and use modified version on your own, 
this is the currently the only one registered package with CQL driver, so I think it's worth to make it more accessible.

I can make necessary PR and create the bridge package between this and JuliaDB if it makes sense.

**Comment by r3tex** [comment]
Sure. PRs are welcome. You can remove the JuliaDB dependency. This package was made long before the table API was a thing.

**Comment by r3tex** [comment]
No prob. Only question is if we should be using the artifacts interface to download the driver, or if it's better to have it as a build step.

**Comment by racinmat** [comment]
I think artifacts would be definitely better. I plan to make new PR which will add also windows support and as part of that I would move the download to artifacts.

**Comment by r3tex** [comment]
Thanks. Looking forward to it.

@JuliaRegistrator register()

**Comment by racinmat** [comment]
You need to add this under the commit itself, not this issue.

**Comment by racinmat** [comment]
Like this https://github.com/r3tex/CQLdriver.jl/commit/cf5788ad8022cebebe787645700dc75799e91de2#commitcomment-43032115 but I can't do it because I don't have rights.

**Comment by racinmat** [comment]
I'm trying to rewrite it to artifacts, but it seems artifacts need to be gzip archives, Pkg tried to unzip it. I'll investigate further.
