### ISSUE TITLE
Please provide authentication for CQL connection

### ISSUE THREAD

**Issue by s439** [r3tex/CQLdriver.jl#2]
My issue is as below.

julia> session, cluster, err = cqlinit("192.168.0.60")
Error in CQL operation: Session Connect
Authentication required but no auth provider set
(Ptr{CQLdriver.CassSession} @0x00000000048c8a90, Ptr{CQLdriver.CassCluster} @0x00000000047bf8b0, 0x0100)

How to provide authentication? Please suggest if I am missing something.

**Comment by r3tex** [comment]
Hey s439, authentication support is missing right now. I'll do my best to add it in the coming weeks but can't promise anything.

**Comment by s439** [comment]
Np, I have added the auth snippet to the source code. If you are ok, I will go ahead and give PR.

**Comment by r3tex** [comment]
That'd be great. Thanks for the help. 
I can make a new release after that so it's added to METADATA as well.

**Comment by s439** [comment]
Hey r3tex, I have given PR #4 #3. Please check

**Comment by r3tex** [comment]
Sorry, was on the road yesterday. Looks good!
One feature I'd like to add is concurrent pulls of queries that return multiple pages.
It'd need some logic to check if futures have reached the last page so as not to spam the server with lots of requests for data that doesn't exist.
Anyway, thanks for the PR. 👍
